setting:
    appId       : xxtime
    appKey      : xxxxxxxxxxxxxxxx
    timezone    : UTC
    cacheTime   : 600
    sandbox     : false
    logs        : false
    security    : 0

dbData:
    adapter     : Mysql
    host        : localhost
    port        : 3306
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8mb4

dbLog:
    adapter     : Mysql
    host        : localhost
    port        : 3306
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8mb4

redis:
    host        : 127.0.0.1
    port        : 6379
    index       : 1
    prefix      : cache_

mq:
    host        :
    port        :
    username    :
    password    :
    vhost       :

sso:
    baseUrl    : http://www.example.com/api/sso/